apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "radome.fullname" . }}-admin
  labels:
    {{- include "radome.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "radome.name" . }}-admin
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "radome.name" . }}-admin
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: radome-admin
          image: "{{ .Values.adminUi.image.repository }}:{{ .Values.adminUi.image.tag }}"
          imagePullPolicy: {{ .Values.adminUi.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            {{- if .Values.adminUi.env.nextPublicApiBase }}
            - name: NEXT_PUBLIC_API_BASE
              value: "{{ .Values.adminUi.env.nextPublicApiBase }}"
            {{- end }}
            {{- if .Values.adminUi.env.nextPublicProxyBase }}
            - name: NEXT_PUBLIC_PROXY_BASE
              value: "{{ .Values.adminUi.env.nextPublicProxyBase }}"
            {{- end }}
