apiVersion: v1
kind: Service
metadata:
  name: {{ include "radome.fullname" . }}-admin
  labels:
    {{- include "radome.labels" . | nindent 4 }}
spec:
  type: {{ .Values.adminService.type }}
  selector:
    app.kubernetes.io/name: {{ include "radome.name" . }}-admin
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 3001
      targetPort: http
